swagger: "2.0"
info:
  description: "Technical test for developing an full api to clients and users"
  version: 1.0.0
  title: Full API for Clients and User
  contact:
    email: "raphael_mendonca@hotmail.com"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:8000
basePath: /api
schemes:
  - http
paths:
  /User:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      parameters:
        - in: body
          name: body
          description: Created user object
          required: false
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
            example:
              name: Client number one
              email: clienr@one
              password: 123
      responses:
        "200":
          description: user created
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
            example:
              processed: true
              message: null
              data:
                name: Client number one
                email: clienr@one
                created_at: "2022-01-10T03:45:29.000000Z"
        "400":
          description: Error in fields requisition
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
            example:
              processed: false
              message: null
              data:
                email:
                  [ The email field is required. ]
  "/User/{id}":
    get:
      tags:
        - user
      summary: get data user dy id
      description: ""
      parameters:
        - name: id
          in: path
          description: "User id"
          required: true
          type: integer
      responses:
        "200":
          description: return data user
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
            example:
              processed: true
              message: null
              data:
                name: Client number one
                email: clienr@one
                created_at: "2022-01-10T03:45:29.000000Z"
        "400":
          description: Error in fields requisition
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  User:
                    type: string
            example:
              processed: false
              message: null
              data:
                User:
                  [ The selected user is invalid. ]
    put:
      tags:
        - user
      summary: Updated user
      parameters:
        - name: id
          in: path
          description: "User id"
          required: true
          type: integer
        - in: body
          name: body
          description: Created user object
          required: false
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
            example:
              name: Client number one altered
              email: clienr@one
              password: 123
      responses:
        "200":
          description: return data user
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
            example:
              processed: true
              message: null
              data:
                name: Client number one altered
                email: clienr@one
                created_at: "2022-01-10T03:45:29.000000Z"
        "400":
          description: Error in fields requisition
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  User:
                    type: string
            example:
              processed: false
              message: null
              data:
                User:
                  [ The selected user is invalid. ]
    delete:
      tags:
        - user
      summary: Delete user
      parameters:
        - name: id
          in: path
          description: The id that needs to be deleted
          required: true
          type: integer
      responses:
        "200":
          description: deleted user
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
            example:
              processed: true
              message: deleted
              data: null
        "400":
          description: Error in fields requisition
          schema:
            type: object
            properties:
              processed:
                type: boolean
              message:
                type: null
              data:
                type: object
                properties:
                  User:
                    type: string
            example:
              processed: false
              message: null
              data:
                User:
                  [ The selected user is invalid. ]
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ""
      operationId: loginUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: false
          type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: false
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when toekn expires
        "400":
          description: Invalid username/password supplied
