version: "3.8"

services:

  mysql:
    image: mysql:5.6
    container_name: "mysql56"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./install-files/init.sql:/data/application/init.sql
    ports:
      - 3306:3306

  php:
    container_name: "php72"
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/html/clientsApi/
    volumes:
      - ../:/var/www/html/clientsApi/
      - ./install-files/php72.ini:/etc/php/7.2/apache2/php.ini
      - ./install-files/apache2.conf:/etc/apache2/apache2.conf
    ports:
      - 8000:80
      - 80:8000

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:5.1.0-apache
    ports:
      - 8888:80
    environment:
      - PMA_HOST=mysql56

  swagger:
    image: swaggerapi/swagger-ui
    container_name: "swagger"
    volumes:
      - ./swagger:/docs
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: /docs/clientApi.yaml
